### PR TITLE
Migrating project to Maven

### PR DESCRIPTION
**Pull request by jainsahab**

### CODE REVIEW

**Comment by reflexdemon** [comment]
@jainsahab,

Can you please update the POM to use the below repository and not the local? Thaks for the help!

``` xml
<repositories>
        <repository>
          <id>central</id>
          <url>https://repo1.maven.org/maven2</url>
          <releases>
            <enabled>true</enabled>
          </releases>
        </repository>
      </repositories>
```

**Comment by jainsahab** [comment]
@reflexdemon the repository you have mentioned, I couldn't find all the dependency there. hence I had to keep the local repository to retain all the dependencies.

**Comment by jainsahab** [comment]
@reflexdemon did you get a chance to have a look on the latest commit ? let me know your views on it.

**Comment by reflexdemon** [comment]
@jainsahab Thanks a lot!

**Pull request merged**
